# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - trainer: default.yaml
  - callbacks: default.yaml
  - datamodule: casia_webface.yaml
  - hydra: default.yaml
  - paths: default.yaml
  - logger: wandb.yaml
  - model: default.yaml
  - recognition: default.yaml
  - external_mapping: default.yaml
  - label_mapping: default.yaml
  - recognition_eval: default.yaml
  - optimizer: default.yaml
  - losses: default.yaml
  - lightning: default.yaml
  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "train"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
# appending lists from command line is currently not supported :(
# https://github.com/facebookresearch/hydra/issues/1547
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 123
prefix: 'test'

