# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_ROOT}
project_task: ${oc.env:PROJECT_TASK}
repo_root: ${oc.env:REPO_ROOT}

# path to data directory
data_dir: ${oc.env:DATA_ROOT}

# path to logging directory
log_dir: ${hydra:runtime.output_dir}

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
